// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf-XorXlF3cQheng6-ewz7R9ytiBPsmo0',
    appId: '1:434685854792:web:caffdd1e8188dac28c047d',
    messagingSenderId: '434685854792',
    projectId: 'planno-b2cfc',
    authDomain: 'planno-b2cfc.firebaseapp.com',
    storageBucket: 'planno-b2cfc.firebasestorage.app',
    measurementId: 'G-VFNTBJEWF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiazrCsoeW85_hbojzQmNRdGhnlQURVXU',
    appId: '1:434685854792:android:7ecb75e8a6b10d408c047d',
    messagingSenderId: '434685854792',
    projectId: 'planno-b2cfc',
    storageBucket: 'planno-b2cfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQnNf25LIIsxgmDA2cSMQfV6Ypp_C2uNg',
    appId: '1:434685854792:ios:3fd7f90deb11d70a8c047d',
    messagingSenderId: '434685854792',
    projectId: 'planno-b2cfc',
    storageBucket: 'planno-b2cfc.firebasestorage.app',
    androidClientId: '434685854792-orts7f8tb07abg7a47fuss47lbe5u37a.apps.googleusercontent.com',
    iosClientId: '434685854792-ea8ug90kgmlcqj9akc0u2vf4idsenuh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasPlanno',
  );
}
